id:
  port: '/dev/book_hand' # linux
  baudrate: 57600
  gripper: 1
  spacer_rot: 2
  spacer_lin: 3

pos:
  gripper:
    close: 3816
    range: 8190 # 4095*2, open: close + range
    release: 400
    theta_zero: 0.252680 # radian
    backlash: 800 # step
    rad_to_step: 651.8986
    step_to_rad: 0.00153398
    gear_ratio: 20
    calib_width_a: 0.9284 #0.9685 #0.9343
    calib_width_b: -8.2664   #-0.3384 #-6.1

  spacer_rot:
    zero: 1473
    range: 8190 # 90 deg # TODO
    backlash: 800 # step
    rad_to_step: 651.8986
    step_to_rad: 0.00153398
    gear_ratio: 20

  spacer_lin:
    back: 3891
    keep: 77803
    range: 160000 #188664 # front: back - range

thresh:
  vel: 20
  pos: 5

cont_gain:
  gripper:
    pos_cont: 50

  spacer_rot:
    pos_cont: 100

