joint_order:
- joint1
- joint2
- joint3
- joint4
- joint5
- joint6
- joint7
waypoints:

- name: p2
  q:
  - -84.4
  - -25.9
  - 188
  - 35.8
  - -159.7
  - 79.6
  - 171.6

- name: p9
  q:
  - -91.9
  - -55.4
  - 173.1
  - 49.7
  - -185.3
  - 93.3
  - 183