joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -58.7
      - -49.9
      - 144.4
      - 72.7
      - 7.3
      - 120.5
      - -207.6