joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -69.5
      - -76.4
      - 154.5
      - 99.8
      - 19.5
      - 119.1
      - -184.6