joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -61.3
      - -50.9
      - 142.9
      - 72.7
      - 3.7
      - 118.8
      - -210.9