joint_order:
- joint1
- joint2
- joint3
- joint4
- joint5
- joint6
- joint7
waypoints:

- name: p2
  q:
  - -84.4
  - -25.9
  - 188
  - 35.8
  - -159.7
  - 79.6
  - 171.6

- name: p11
  q:
  - -94.7
  - -56.9
  - 167.3
  - 52.2
  - -191.1
  - 93.3
  - 187.4