joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -67.2
      - -76.2
      - 155.5
      - 100.4
      - 22.5
      - 120
      - -181.9