joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -65
      - -76.2
      - 156.3
      - 101.4
      - 25.5
      - 121
      - -179.3