joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -56.7
      - -49.3
      - 145.7
      - 73.1
      - 10.4
      - 121.9
      - -204.8