joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -61
      - -77.2
      - 157.7
      - 105.1
      - 31.9
      - 123.2
      - -173.5