joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -55.3
      - -81.4
      - 157.9
      - 115.2
      - 43.4
      - 127.6
      - -163.8