joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -71.8
      - -76.9
      - 153.3
      - 99.8
      - 16.8
      - 118.4
      - -187.3