joint_order:
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
waypoints:
  - name: p4
    q:
      - -74.2
      - -77.8
      - 151.9
      - 100.4
      - 14.1
      - 117.7
      - -190.1