joint_order:
- joint1
- joint2
- joint3
- joint4
- joint5
- joint6
- joint7
waypoints:

- name: p1
  q:
  - 61.8
  - -78.4
  - 179.6
  - 99.7
  - 184
  - -18.8
  - -209.4   

- name: p2
  q:
  - 69.43
  - -73.38
  - 178.46
  - 102.45
  - 184.78
  - -6.08
  - -203.18

- name: p3
  q:
  - 13.8
  - -88.6
  - 176.8
  - 67.5
  - 180.3
  - 21.5
  - -78.6